### ISSUE TITLE
Filename Incompatible with Windows

### ISSUE THREAD

**Issue by ambsw-technology** [binxio/cfn-lb-ip-address-provider#1]
I assume that's why I can't checkout master...

> git.exe checkout master --
> D	docs/Custom::LBIpAddress.md
> Your branch is up-to-date with 'origin/master'.
> error: unable to create file docs/Custom::LBIpAddress.md: Invalid argument

Seems to be confirmed by [this SO answer](https://stackoverflow.com/a/10386576).

**Comment by mvanholsteijn** [comment]
thank you for the patch! Merged
