### ISSUE TITLE
Wrong Provider Name?

### ISSUE THREAD

**Issue by ambsw-technology** [binxio/cfn-lb-ip-address-provider#2]
I'm having a hard time even figuring out where this is defined, but I built a Lambda Test when I was having issues and eventually landed on...

    {
      "Status": "FAILED",
      "Reason": "ResourceType Custom::LBIpAddresses not supported by provider Custom::LBIpAddress",
      "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/MyStack/guid",
      "RequestId": "unique id for this create request",
      "LogicalResourceId": "MyTestResource",
      "Data": {}
    }

**Comment by ambsw-technology** [comment]
OK found it in the base class.  Obviously the issue is still valid.

**Comment by mvanholsteijn** [comment]
thank you for your contribution. fixed!
