### ISSUE TITLE
Unable to download the zip file

### ISSUE THREAD

**Issue by ninjonxb** [binxio/cfn-lb-ip-address-provider#5]
I am getting errors when I try to either download the zip file directly or use it through lambda.
I am getting 404 errors

```
~ aws s3 cp s3://binxio-public-us-east-1/lambdas/cfn-lb-ip-address-provider-1.0.0.zip .
fatal error: An error occurred (404) when calling the HeadObject operation: Key "lambdas/cfn-lb-ip-address-provider-1.0.0.zip" does not exist
```

I am also trying to just build this manually but I keep running into errors related to `cfn_resource_provider`. When I look through the build files I don't see how this is being included. I have it in the requirements.txt file but it is not working. When I try to just put the source for that in `cfn_resource_provider` it still fails.

**Comment by mvanholsteijn** [comment]
Sorry @jonheckman , the build pipeline was broken and I had not noticed.

The version is available now.

**Comment by mvanholsteijn** [comment]
To build it manually, you should just type `make`.
